[package]
name = "clamp"
version = "0.1.0"
authors = ["Takeshi Tsukamoto <dev@itome.team>"]
edition = "2018"

[dependencies]
rustyline = "5.0.3"
lazy_static = "1.4.0"
regex = "1.3.1"
itertools = "0.8.0"
fnv = "1.0.6"
